{
 "title": "Air Quality Sensor",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Particulate Matter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µg/m³" } },
   "targets": [
    { "expr": "pm02{}", "legendFormat": "PM 2.5" }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    { "expr": "rco2{}", "legendFormat": "CO2" }
   ]
  },
  {
   "title": "Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    { "expr": "atmp{} *1.8 + 28\r\n", "legendFormat": "Temperature" }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    { "expr": "rhum{}", "legendFormat": "Humidity" }
   ]
  }
 ]
}